### ISSUE TITLE
presense tracking

### ISSUE THREAD

**Issue by sergeyt** [edu-xored/tyt#13]
* [x] single button to report presence
* [x] button "I am here" is enabled for some role and within some time interval
* [x] `POST /api/iamhere` endpoint
* [x] allow to send presence status from given list of IP addresses, i.e. to report presence only via given wify access point
* [ ] do not allow to post presence event using `POST /api/events`
